service:
  update_interval: 10 #Seconds
  log_level: error

mqtt:
  ## Use mqtts for SSL support
  broker: "mqtt://192.168.1.10:1883"
  user: admin
  password: password
  client_id: aircac2
  topic_prefix: aircon2
  auto_discovery_topic: homeassistant
  auto_discovery_topic_retain: false
  ## CA certificate in CRT format.
  # certificate_authority: "./config/cert/ca.crt"
  ## Don’t verify if the common name in the server certificate matches the value of broker
  # skip_cert_cn_check: true
  ## Authorization using client certificates
  # certificate_client: "./config/cert/client.crt"
  # key-client: "./config/cert/client.key"

devices:
  - ip: 192.168.66.11
    mac: C8F742DFA4FA
    name: Folyosó
    port: 80
    temperature_unit: C
  - ip: 192.168.66.15
    mac: 34EA34901881
    name: Nappali
    port: 80
    temperature_unit: C